<!DOCTYPE html>
<html lang="en-US">
<meta http-equiv="content-type" content="text/html; charset=utf-8" /> 

<head><title>IC - Dragon Introduction and Adventure Leveling Guide</title>
	<!-- SCRIPTS -->
		<link rel="stylesheet" type="text/css" href="../style.css" media="screen" />
		<link rel="icon" type="image/png" href="../images/favicon32.png" sizes="32x32" />
		<link rel="icon" type="image/png" href="../images/favicon16.png" sizes="16x16" />
	<!-- END SCRIPTS -->

<!-- HEADER IMAGE -->
	<a href="../index.php"><img src="../images/istaras_chosen_logo.png" id="logo" /></a>
	<img src="../images/header_screenshot.png" id="headerscreenshot" />
<!-- END HEADER IMAGE -->
</head>
<body id="main" onload="homeNavigation(); sidebar();">
<section>
	<!--BEGIN NAVIGATION -->
	<div class="navbox">
		<?php include("../navigation.html");?>
	</div>
	<!-- END NAVIGATION -->
	<article>
		<header class="article border">Dragons: An Introduction and Adventure Leveling Guide</header>
	<p style="font-size:.75em">Written by Racktor August 1st, 2018 - May 13th, 2020</p>
			<br/>
			<center><i><a href="index.php">&larr; Return to Guides</a></i></center>
			<br/>
			<ul>
				<li><a href="#intro">Introduction</a></li>
				<li><a href="#build">Making a Basic Build</a></li>
					<ul>
						<li><a href="#tp">Training Points</a></li>
						<li><a href="#scales">Scales</a></li>
						<li><a href="#claws">Claws</a></li>
						<li><a href="#spells">Spells</a></li>
						<li><a href="#summary">Summary</a></li>
					</ul>
				<li><a href="#combat">General Combat Tips</a></li>
				<li><a href="#adventure">Leveling Your Adventure School</a></li>
					<ul>
						<li><a href="#t1">Tier 1 - Lv. 0 to 19</a></li>
						<li><a href="#t2">Tier 2 - Lv. 20 to 39</a></li>
						<li><a href="#t3">Tier 3 - Lv. 40 to 59</a></li>
						<li><a href="#t4">Tier 4 - Lv. 60 to 79</a></li>
						<li><a href="#t5">Tier 5 - Lv. 80 to 100</a></li>
					</ul>
				<li><a href="#rites">The Rites of Passage</a></li>
					<ul>
						<li><a href="#factions">Helian or Lunus?</a></li>
						<li><a href="#rop">Adult Rite of Passage</a></li>
						<li><a href="#arop">Ancient Rite of Passage</a></li>
					</ul>
			</ul>
			<br/>
		<a name="introduction"><header class="subsection border">Introduction</header></a>
		<p>Dragons are Istaria's flagship race. Its entire marketing is based around them, so to play one, you must be really good and know how to do everything right or else you die, correct? Actually, no - dragons are notoriously easy to level and understand. Unlike bipeds, who have nearly fifty schools combined between adventure and crafting, dragons only have one adventure school and three crafting schools. They have a very smooth set path for leveling if you follow ability quests. They also gain the power of flight - an extremely useful skill for traverseing terrain - quite early. If you are new to Istaria, the best place to start learning the game is certainly a dragon.</p>
		<p>The first thing to know when starting up a dragon is that you are strong. In lower levels, be careful not to overestimate yourself, but your power scales up dramatically as you unlock new scale slots and upgrade your equipment. When you start, you may struggle to take down even the little grulets in Skalkaar, but by level thirty you can easily smack down level fifties if you know how to work your abilities and have good gear. Level fifties and sixties can take down the highest level enemies in the game, shy of epics. As a group, dragons are unstoppable. Alone, they’re still formidable. Take advantage of that!</p>
		<p>That being said, the second thing to be aware of is what path you want to take. There’s multiple ways to level a dragon; they only have one adventure school and one primary craft school and thus are considerably easier than the much squishier and more complex bipeds. Do you want to not bother with upgrading your scales as you go and wish to slaughter enemies even at level one? Level your craft to eighty or ninety first and equip tier five scales - nothing will stand in your way for a very long time. Hate crafting and just want to run ahead? That works too. Dragons are very flexible when it comes to leveling strategies.</p>
		<p>Regardless of what crafting path you take, leveling adventure is very similar all the same. Before we delve into the actual leveling aspect of playing a dragon, let's consider the basic build mechanics and how setting up your training points and scales works.</p>
		<a name="build"><header class="subsection border">Making a Basic Build</header></a>
			<p>Before we start, let’s cover their basic statistics and skills so you understand what you’re looking at in your training points window. We go far more in detail with this on the <a href="http://istaraschosen.com/resources/dragonbuilds.php" target="_blank">Introduction to Dragon Builds</a> page, so check that out if that is more what you’re looking for. This is a simple overview!</p>
				<a name="tp"><header class="subsection2 border">Training Points</header></a>
				<p>The first encounter with creating a build you will have is with your training points. Training points are points that you can spend in exchange for certain statisics. Listed below are the available stats you can skill.</p>
				<ul>
					<li><b>Strength:</b> Directly increases physical damage. Costs 4 points.</li>
					<li><b>Power:</b> Directly increases magic damage. Costs 4 points.</li>
					<li><b>Primal:</b> Increases damage and accuracy of spells that use the primal skill. (Essentially all dragon spells) Costs 3 points.</li>
					<li><b>Tooth and Claw:</b> Increases damage and accuracy of physical attacks that use the tooth and claw skill. (Essentially all attacks) Costs 3 points.</li>
					<li><b>Dexterity:</b> Increases your to-hit chance with physical abilities and decreases an enemy's. Costs 4 points.</li>
					<li><b>Focus:</b> Increases your to-hit chance with magic abilities and decreases an enemy's. Costs 4 points.</li>
					<li><b>Health:</b> Directly increases your health pool. Costs 1 point.</li>
					<li><b>Evasion:</b> Increases your chance to dodge an enemy's physical attack. Costs 3 points.</li>
					<li><b>Magic Evasion:</b> Increases your chance to dodge an enemy's magical attack. Costs 3 points.</li>
				</ul>
			<p>From this list, you'll notice two major distinctions: magic and physical damage. Depending on what you want to play as - a dragon spellcaster (henceforth referred to as 'caster') or a physical attacker/melee dragon (melee) - you will want to skill specific stats related to it. If you are a melee-focused character, then don't put anything in primal, power, or focus, for instance. Regardless of which category you are looking for, it is not recommended to skill anything into the evasion, dexterity, or focus - these statistics are largely useless to you and do not make enough of a notable difference in my testing.</p>
			<p>Especially when leveling, the unique statitic health is very useful to skill. If you put a lot of points into health, you will directly see those points returned as hitpoint. 600 training points into health means 600 hit points.</p>
			<p>Keep in mind when skilling statistics that you can only ever place half of your maximum points into one category, limiting you to fully filling two bars.</p>
			<p>Knowing all of this, now, here are the usual primary statistics that you will likely focus on. As a <i>melee</i>, you will likely skill strength, tooth and claw, and health. Focus on health if you want survivability, and otherwise focus on a split between strength and tooth and claw if you want to be more of a glass cannon.</p>
			<p>Similarly, for <b>casters</b>, focus on power, primal, and health. For <b>hybrids</b> (dragons that use both spells and melee skills interchangeably), you will want to strike a balance between the two. Hybrids become more viable the higher level you are, as you can diversify your scale stats and eventually use tier six scales, so it may be better to focus on one side of the spectrum until you are around mid tier.</p>
					<a name="scales"><header class="subsection2 border">Scales</header></a>
						<p>Dragon armor pieces are known as scales, which cover ten portions of the body. You unlock a new scale slot every ten levels, starting with the chest at level 1. In order  - first wing, head, second wing, first foreleg, first hindleg, second foreleg, second hindleg, back, and tail slots.</p>
						<p>Scales follow a pattern - each scale offers a +X boost to a particular attribute, as well as a base +Y armor increase. The "X" attribute can be any of the following: strength, power, focus, dexterity, armor, or health. As mentioned prior with training points, completely disregard focus and dexterity.</p>
						<p>As with your build, you will want to choose a type of scale based on your build's primarily attribute. Now, here you can also choose armor. Armor is useful in its own right, but you need <i>twelve points of armor to reduce one point of damage</i>, approximately. To gain the same amount of "effective health" (as that is, in essence, all that armor is) as you do actual health from health scales, you would need <i>twelve times</i> the statistic. Therefore, if you are choosing to make a more tanky build, it is recommended to focus on health rather than armor.</i>
						<p>In short: if you are a melee dragon, use either strength or health base scales. For caster, use power or health. Hybrids can use a mix of power/strength scales or just full health techniqued with a variety of mix-matched statistics.</p>
						<p>On the line of techniques - <i>do not stress over them</i>. Until about tier three, techniques do so little to your statistics overall that it isn't that big of a deal to run with or without them. They do help, but they aren't necessary to your survival. For tiers three, four, and five, they become more important. (A full level 30 scaleset can, at most, provide you with +40 of a single statistic.)</p>
						<p>However, it is difficult to hunt down and craft all the necessary pieces for a full armor set, especially if you are a solo player entering a new tier. <b>Remember that having an unteched tier 4 scaleset is better than running a fully teched tier 2 scaleset.</b> If you cannot get your hands on a decked out scaleset, that is fine, but at least try and upgrade your armor to the next base level. If you don't have the crafting level, there are many people in the game who are likely willing to craft it for you provided you hunt the base components yourself if you want techniques. (Myself included, if you happen to run into me in-game!)</p>
						<p>A very important thing to note about dragons is that their scales are also based on adventure <i>or</i> craft level, meaning that even at a level 1 adventure, you can wear level 80 scales. This will make you exceptionally powerful early on and remain useful all the way until you are an ancient dragon. However, it <i>does</i> require you to level your craft first, which is not something many players enjoy doing. Naturally, as this is an adventure guide, craft won't be covered here!</p>
						<p>I will not get too in depth into the actual process of creating and techniquing a scaleset as most of that is covered by in-game tutorials and the combinations are covered by the other build guide on this site. However, I want to bring up two important points to remember:</p>
						<p><i>Scale technique slots vary by tier.</i> Tier one and two can only have one technique, rendering them vastly useless.  Tier three and four have two, and tier five has three. (Repaired tier 6 scales have 2, but that is a unique case.) Be wary if you plan to tech your scales and use a program like Horizons Crafting Calculator!</p>
						<p><i>Only some scales can have sockets.</i> Socketed scales can hold crystals, which are dropped by various mobs (primarily Aegis-type enemies and undead) or given by quests. They are useful, but only if you have some on hand that have your skill or you obtain good quest-related ones. However, sockets can be dragged onto scales post-creation, so they are useful to have on hand regardless as they can be added in any spare technique slot without any crafting level. The scales that can hold sockets are chest and foreleg (armor slots) and head (jewelry) scales.</p>
						<p><i>You cannot get quest techniques back easily.</i> Lots of quests in the game give unique technique kits, but many can be a grind to get back if you apply them to the wrong scale. Most lower-level ones are weaker bonuses that can be used just as a filler, but some techniques are good to save for higher levels - like the Fiery Rose Quartz Shard. At a high level, it is easier to regain a technique the lower-level you got it, so don't be too scared to mess up, as well.</p>
					<a name="claws"><header class="subsection2 border">Claws</header></a>
						<p>Dragon weapons are known as claws, and come in only one variety, upgrading every few levels. Claws are much simpler in comparison to scales, but they have a few things worth mentioning. In testing, it is revealed that claws only ever <i>increase</i>, your damage, but it never caps your damage. Your actual damage comes from the 'Claw Mastery' passive you get from leveling up, and then claws add onto that. Do not stress about adjusting claws every 6 or so levels; it is not that important and won't hurt you to use a lower-level claw. They can only help.</p>
						<p>The real point of claws is to give dragons a place to technique a weapon with specific weapon-based effects, much like bipeds have swords or daggers. It is essentially another 'scale' to add a technique to, in terms of attributes and skills, but it can accept a few unique things.</p>
						<p>Claws can be socketed much like chest/foreleg/head scales, but they accept weapon (or claw) sockets. These sockets take weapon crystals, which can be just like regular armor crystals with stat boosts, give unique on-hit effects such as extra damage procs, and a few other unique bonuses from quest-specific ones like damage converters. Any extra damage is better than none at all, so if you have a spare crystal with bonus damage around and nothing else to put on your claw, do so.</p>
						<p>Secondly, claws have a large selection of what's known as crafted dragon technique kits. These technique kits are techniques that can be crafted seperately from the item itself, and drag-n-dropped onto it later to apply. The formulas to create these are max level, so you will have to ask for them if you don't have high enough of a craft level, but the kits themselves are pretty useful. It is best for you to do your own research on what you personally prefer, as there are a good handful, but the most common choices are Battle-Forged for melee and Deadly for casters. Either or works for hybrids, as you cannot stack the tech kits.</p>
					<a name="sspells"><header class="subsection2 border">Spells</header></a>
						<p>Spells are another point that many new players look over in adventuring. Many MMOs will give you your spells, but in Istaria, you have to craft them - and a lot of the formulas are drop-only, resulting in an issue acquiring everything by yourself.</p>
						<p>For melee dragons, you truly could technically level entirely without a single spell. However, you still will want buff spells - these spells are self-casted bonuses, such as increases to your damage or health. In the beginning tiers, it's not very worth getting - such as tier 1 or 2 - but once you reach tier 3, it starts getting more impactful if you have your buffs.</p>
						<p>For casters, as their name implies, you need all of your damaging spells. You can find a list of every spell in the game that dragons can use <a href="http://www.istaria-lexica.de/Primal#Total_Spell_List" target="_blank">here</a>. With the exception of Drain Bolt, which is obtained through a <a href ="http://www.istaria-lexica.de/Khemarius" target="_blank">questline</a> (which is highly recommended - almost required - for Casters), all of the spells can be crafted by others for you. Ask kindly and you may find someone willing to craft you unteched versions of the spells for each tier - cost depends on the person, naturally, but you aren't going to be paying a ton of coin for a simple task, I'm sure.</p>
						<p>For tier three and above, remember that any buff is a buff - even if you only have tier three buffs, keep using them on yourself until you get higher tier ones. Don't cop out just because they're lower level. Any increase is an increase; help is help!</p>
						<p>Spells are also like scales in which their <i>effects</i> are based on adventure or craft level, for most things. If you see someone around, feel free to ask them to buff you with tiers higher than you personally can use, if your craft is appropriate.</p>
				<a name="summary"><header class="subsection2 border">Summary</header></a>
					<p>A basic summary, to conclude this drawn-out background information, is this:</p>
					<p>If you plan to build a <b>caster</b> dragon, focus on power, primal, and health. For <b>melee</b> - strength, tooth and claw, and health. <b>Hybrids</b> are a balanced combination between the two, becoming more viable the higher level you are and thus more numbers you can work with through scales.</p>
					<p>Do not worry about techniquing scales until tier three, and even then, it's more important to upgrade the base scales, even unteched, as you level. Higher-level older players are more than willing to help with non-technique related things.</p>
					<p>Claws do not cap your damage and don't need to be worried about on the same level as scales. If possible, add Deadly (caster) or Battle-Forged (melee) to your claws.</p>
					<p>Spells are important for casters and far less so for melee, but all characters should at least have buff spells. Ask others if you cannot craft them yourself.</p>
			<a name="combat"><header class="subsection border">General Combat Tips</header></a>
				<p>Dragon combat - and combat in Istaria - is very easy to get the hang of as a whole. You can go far advanced into specific skill rotations and managing your damage output with certain multiplier windows, but that truly is not needed for any of the game unless you are looking to solo epic monsters, which is far beyond the scope of this guide.</p>
				<p>As a whole, dragons will fight similarly between caster and melee. The biggest change is what to fill with in between your auto attacks and what your bursts are. For both types, though, you should always be trying to use Snarl and Staggering Howl when you acquire these abilities. These two are very useful debuffs which increase your enemy's chance to miss or lower their attack speed respectively. This greatly increases your survivability in turn - if you are having issues, trying using those abilities.</p>
				<p>Stances should be used depending on your situation. If you keep getting beaten down, use Soldier's. If you want more damage, use Conquerer's or Primalist's depending on your build. In later levels, it is arguable that Attuned stance is better, as it lowers your delay by 5% which may result in a higher effective damage than the other two stances, but it stands to be proven. Regardless, it is helpful in its own right. The other stances are less effective and the buff Protection should never be used - it reduces your damage to 25%, making fighting a slog. Don't use it unless you're trying to tank!</p>
				<p>A defensive skill shared between all builds is Spiked Scales, which gives you a damage shield. You do damage to enemies that hit you, so it is especially useful in groups. Shield of Gold, gained upon ascension to adult, gives you a very intense damage shield that absorbs damage and converts it into hoard drain. This is a very useful emergency  button for healing or escape, so hold off until you're sure you need it!</p>
				<p>Use Primal Cast to cast Breaths or Spells multiple times in one cast - though this is a level 100 only ability gained through a quest, so it won't be available for a long time to a new player.</p>
				<a name="conqueror"><header class="subsection2 border">Melee</header></a>
					<p>As a melee dragon, your bread and butter is Gold Rage. This attack not only does massive outgoing damage, but it also reduces your enemy's attack speed and resistance to further primal attacks (which you should be doing if you are using Primal Attack). Follow it up with Ravage, Silver Strike, and Drain Strike. These there are very useful damaging abilities. The last is also a heal, and can be conserved in longer fights to recover health if your other heals are on cooldown.</p>
					<p>Your other useful abilities include Galewind, Tail Whip, Bite, and your breaths. Tail Whip is a stun and good to give an opening for healing. Galewind does a good amount of damage if augmented with Piercing Winds (a technique kit). Bite is a damage-over-time that you can use early to give some extra damage over the fight. Your Breaths are a unique aspect of dragonhood, with Breath of Fire being your only initial breath attack. As you ascend and level, you will learn other breaths - such as Breath of Ice, Lightning, Acid, and Flame Burst, to name the non-epic ones. In order: they slow enemy's attacks, dispel buffs, do a massive damage-over-time, or deal massive area-of-effect damage. Use these throughout the fight to increase your damage output.</p>
					<p>Be aware that Ice Breath conflicts with the debuff from Gold Rage, so always use it <i>after</i> Gold Rage to get the better debuff on first!</p>
				<a name="primalist"><header class="subsection2 border">Caster</header></a>
					<p>Be 100% sure you always have Drain Bolt. Drain Bolt is the caster's auto attacking murder button - not only does it do decent damage on a relatively fast repeat, but it also heals you with every hit, keeping you alive. In most situations, you can simply cast this on repeat until your enemy is dead, though this is a bit dull.</p>
					<p>A caster's pièce de résistance of single-cast damaging spells is Primal Burst. It can only be upgraded three times, with Primal Burst III being the highest it can go. It is a very intense multistriking damage spell that can also be augmented with Primal Cast to add yet another hit. Be sure to hit this off as your first attack or during midfight - with its longer cooldown, you don't want to waste it when something is almost dead! It is linked with Gold Rage, so you cannot use both at once.</p>
					<p>Following this, you have Primal Strike as another damaging spell. It is linked with Silver Strike and functions as a double-hitting simple damage spell.</p>
					<p>Primal Spark does okay damage and is a stun and Primal Chains is a rooting spell. Use these to keep enemies at bay if you need to move away or escape.</p>
					<p>Otherwise, a caster will use their Breath attacks a lot. As mentioned in the melee section, your Breaths are a unique aspect of dragonhood, with Breath of Fire being your only initial breath attack. As you ascend and level, you will learn other breaths - such as Breath of Ice, Lightning, Acid, and Flame Burst, to name the non-epic ones. In order: they slow enemy's attacks, dispel buffs, do a massive damage-over-time, or deal massive area-of-effect damage. Use these throughout the fight to increase your damage output.</p>
					<p>Otherwise, if all is on cooldown, simply autocast Drain Bolt.</p>
		<a name="adventure"><header class="subsection border">Leveling Your Adventure School</header></a>
			<p>As the name not so subtly replies, Dragon Adventurer is your adventure school - and the only one you will ever have as a dragon. It is a relatively simple school, featuring a host of level-gated abilities and no necessarily complicated mechanics to wrap your mind around.</p>
			<p>You can reference which abilities you will gain as you level up from <a href="https://istariareference.com/schools.asp?school=Dragon+Adventurer" target="_blank">Istaria Reference's page</a> for the school. This also lists which stats you will gain per level-up and how many, as well as where the school NPCs are located. (For all intents and purposes, however, these school NPCs are relatively useless to your experience.)</p>
			<p>When you start leveling your adventure school, you will be going through the tutorial islands and end up at approximately level 10 to 15 when you reach Kion, the beginning of the open world and the main game. This is where our guide will start.</p>
			<p>Dragons are unique in the fact that they gain most of their powerful abilities through what are known as <i>ability quests</i>. A dragon without its abilities is essentially a fish out of water; you lack a vast majority of your harder hitting skills, your best heal, and useful passive abilities. Make sure you do your ability quests!</p>
			<p>These quests are also your best bet to leveling up. As you get the next version of an ability every 10 levels, and the quests are broken up into two staggered groups - ones that upgrade at level x0 and ones that upgrade at x5 - they provide an excellent (if relatively repetetive) structure to follow to  reach max level.</p>
			<p>Your first ability quests will be found in Kion, from the dragon on the vault roof named Gerix. Take and do all of the ones that give abilities. There are a few that he offers that are small story quests, which you can do too, but are less important than your ability quests. If you need help on the specifics of the quests, please refer to the informational websites for Istaria - the Lexica or the Wiki.</p>
			<p>After Kion, ability quests are split between two major cities - Dralk and Chiconis. These cities are where all of your future trainers will lie and where you will come back to. A helpful reference is the <a href="http://istaraschosen.com/resources/dragonreference.php#adventuring" target="_blank">Dragon Reference</a> page, in which you can see the locations of, names of, and abilities given by the trainers in both cities.</p>
			<p>You will notice that from now on, effectively, your leveling pattern is going to be doing your ability quests, then capping off your level to the next X0/X5 and picking up more quests. Make sure you turn in trophies from the monsters you hunt for your quests for extra experience. Each tier has different quests to take on to reach your next X0/X5 level, and many can give very helpful crystals and techniques to push you on your way. If you can't manage to do your ability quests at your current level, take a break and hunt trophies for trophy hunters or work on side quests or story quests to increase your level. Below, I'll go into more depth as to where to look in each tier.</p>
			<p>It is generally recommended that you level your craft school up to 80 or 90 first at the least before starting adventure. It is certainly not necessary, and I never do so, but it will make your experience infinitely easier - you will be wearing armor meant for level 80-100 at level 1, making you far more powerful than your surrounding monsters. Of course, if this is not your playstyle, you don't need to; it is entirely up to you.</p>
			<p>Finally, if you are lost, always check <a href="https://istariareference.com/istariamap.asp" target="_blank">Istaria Reference's map</a> for your target! Simply search for what you are looking for and the map will find it. Alternatively, you can always install the Map Pack Mod version of the map into your game, as well, which gives you all the markers on the in-game map for spawns.</p>
					
				<a name="t1"><header class="subsection2 border">Tier 1 Tutorials and The Lesser Aradoth</header></a>
					<p>If you are reading a guide, I'm assuming you have gone past Skalkaar and New Trismus and are in Kion, where the game stops holding your hand and drops you into the world. If not, follow the tutorials in Skalkaar and the main story questline in New Trismus - these will get you to a decent level before you reach Kion, and give you a good grasp on the game. The region around Kion is balanced for level 10, so if you are stuck or do not wish to finish New Trismus' questline, you can move on from there.</p>
					<p>In Kion, Gerix will be your ability quest trainer - and your only one for this tier. Pick up all of the quests you can from him and set out to do them. Generally, they should get you near 15 (for the X0 quests) and a bit below 20 for the X5s, as they give little experience and the trophies you gather give nil to none.</p>
					<p>For being stuck below 15, Kion has some quests for you to pick up. At level 10, you can pick up the first of the main storyline of the game (currently unfinished) called <a href="http://www.istaria-lexica.de/Story:_A_Disturbance_of_Spirit_(Part_1)" target="_blank">Story: A Disturbance in Spirit</a>. This questline leads you a long way through the continent and to your very first dungeon, which can be very tough alone. This questline will give a lot of experience and lasts a long time, so it is helpful to do to get a leg up on your ability quests if you are having trouble. The rewards, however, aren't particularly useful.<p>
					<p>If you're stuck below 20, a good questline to do is the <a href="http://www.istaria-lexica.de/Sslanis_Militia:_Quakes_and_Disturbances_(Part_1)" target="_blank">Sslanis Militia questline</a>. It starts at level 16 with Captain Kerrak in Sslanis, and leads up to another tier one dungeon. The quests can be hard on-level, so bring friends, or try to outlevel it a little using trophies or town marshall quests. Before the final quessts in the questline, you have the option to pick up <a href="http://www.istaria-lexica.de/Bones_of_the_Ancestors" target="_blank">Bones of the Ancestors</a>. This rewards you a crystal that slots into an armor socket called the Sigil of Kaasha. It is an extremely useful heal-over-time that can help you in your lower levels.</p>
					<p>Once you are level 20, be sure to pick up Gerix's "Journey to Chiconis" quest to receive free experience for simply walking to Chiconis.<p>
				<a name="t2"><header class="subsection2 border">Tier 2 - The Dalimond Peninsula</header></a>
					<p>At this point, you are split into two cities for your ability quests. Refer to the reference sheet I linked earlier for locations - and remember, for ease of picking up quests, you can greet NPCs from 100 meters away!</p>
					<p>Tier 2 is one of the worst sinks for a lack of experience. Your ability quests won't get you to the next requirement for your abilities often, leaving you to hunt for trophies that give pretty abysmal experience with a rather painful drop rate in a lot of cases.</p>
					<p>Unfortunately, the story quests are also long, hard, have little reward, and give almost no experience. On the upside, tier 2 is when you meet the minumum requirements for the Adult Rite of Passage! This questline does give a lot of experience, so if you are someone aiming to fly without waiting for the level 50 mark (the recommended level, as well as the level you receive your Lv. 50 hatchling scales), you have a leg up.</p>
					<p>An important quest pops up during tier two as well. Be sure to seek out Vladtmordt and obtain your <a href="http://www.istaria-lexica.de/Vladtmordt%27s_Replica_Scale_of_the_Prime" target="_blank">Replica Scale of the Prime</a> and <a href="http://www.istaria-lexica.de/Vladtmordt%27s_Replica_Tempered_Scale" target="_blank">Replica Tempered Scale</a>. These chest scales cannot be socketed, but they give a good stat increase for your level and will remain useful at least until tier 3.</p>
					<p>Otherwise, the big questline of tier two is <a href="http://www.istaria-lexica.de/Category:Plundered_Tombs_questline" target="_blank">The Plundered Tombs</a> questline. It gives very little experience on each quest end, and can be pretty rough, but it gives you something to do in between waiting for quests that isn't grinding. It starts in Sable Shore with <a href="http://www.istaria-lexica.de/Elissa_Malna:_Lost_Cargo_Disk" target="_blank">Elissa Malna: Lost Cargo Disk</a>. According to the developers, this is the longest unbroken questline in the game. This leads you to the Ashlander's Tomb dungeon, a very hard, but interesting, dungeon for tier two.</p>
					<p>An upside of the Plundered Tombs as a dragon is that it also leads into the <a href="http://www.istaria-lexica.de/Category:Helian%27s_Tomb_questline" target="_blank">Helian's Tomb questline</a>. This is the other tier two dungeon. The questline's end gives you a somewhat useful stone for your level, another armor crystal called "Battlemaster's Stone" that gives +25 primal and tooth and claw. You also get the title Helian's Protector which gives an addition +20 TnC/primal. As a warning, this questline runs through nearly all of tier two, and requires increasingly higher levels, so you may need to stop and find alternative sources of experience in-between picking up quests.</p>
					<p>At the very end of tier two, there are some quests in Tishlar that  lead up to the next tier - which focuses on Cults, beginning with the Cult of Scorpus around Tishlar and Dryart. If you are struggling, try to <a href="http://www.istaria-lexica.de/Tishlar" target="_blank">check out what Tishlar has in store for you.</a><p>
				<a name="t3"><header class="subsection2 border">Tier 3 - The Barasavian Desert</header></a>
					<p>You're nearing the halfway point! Congratulations! If you are still a hatchling here, be sure to check out Vladmordt again at level 50 to obtain your level 50 hatchling scales. While they are not documented on the Lexica as of writing, Vladtmordt does offer them to you. These scales are useful up to tier five. Be sure to <a href="http://www.istaria-lexica.de/Valley_of_Repose" target="_blank">do the attunement quests if possible</a> for Trandalar, as you will find yourself running for miles during your rites otherwise.</p>
					<p>Tier three is where it picks up for good experience-giving quests after the T2 drought. If you did the cults quest around Tishlar, you can do <a href="http://www.istaria-lexica.de/The_Tomb_of_Ada-Korrous" target="_blank">one final Tomb</a> quest or be pushed towards the <a href="http://www.istaria-lexica.de/Plans_Within_Plans" target="_blank">beginning of the Tower of Healing</a> quests. The Memories of the Fallen questline in the Tower of Healing region gives you a supremely useful technique kit that adds Primal and Health, if you wish to pursue it.</p>
					<p>Starting at 45, you can find the next Cult questline with the Cult of Telak up in New Rachival, starting with <a href="http://www.istaria-lexica.de/The_Renegades" target="_blank">The Renegades</a>. Due to the concentration of mobs in this region, it's recommended you wait some time or bring friends.</p>
					<p>Also starting at level 45 is the very long and interesting content regarding the fall of the capital city Tazoon to the east of New Rachival, with quests starting in the <a href="http://www.istaria-lexica.de/Granite_Hills_Camp" target="_blank">Granite Hills Camp</a>. From here, you can obtain quite a few good rewards - like, from the Bones of a Master questline, the Legacy of Ambirannis, a crystal that gives a whopping +125 tooth and claw and primal. This crystal is useful until endgame, so be sure to get it!</p>
					<p>Be sure not to miss the questline starting with Shau, either, who you are led to from one of the Imperial Army Camp quests.</p>
					<p>Past 50, you are on a quest decline once more, with the only quests available being the <a href="http://www.istaria-lexica.de/The_Scourge_of_Akkinelos_(Part_1)" target="_blank">Scourge of Akkinelos questline</a>. If you're struggling to hit level 60, try to gear up and kill level 90-100 golems - such as Emerald Golems. They are relatively easy as they do not overburden you, but give a lot of experience due to being much higher level than you. Otherwise, you're looking at a trophy grind if your ability quests don't do the trick.</p>
				<a name="t4"><header class="subsection2 border">Tier 4 - Dralk and Kirasanct</header></a>
					<p>Unfortunately, tier four is barren of quests. The development team of Istaria has been revamping and adding more quests to the game tier-by-tier - tier three is current, so hopefully tier four is soon. For now, you're looking at a long dull grind of ability quest - trophies - ability quest - trophies.</p>
					<p>In these levels, you can probably start taking on monsters that are over level 100, but be careful - you will need good gear for it.</p>
				<a name="t5"><header class="subsection2 border">Tier 5 - The Aradoth Frontier</header></a>
					<p>You're in the last stretch! At this point, you will also notice that most of your ability quests stop at VIII (8) or VII (7) for Gold Rage, leaving you on even more of a grind than prior. The last two quests are locked behind ascending to ancient at level 100, and therefore are unobtainable for you as of now. Your only remaining ability quests will be your passives - Accurate Breath, Hardened Scales, Tooth and Claw Mastery, and Primal Mastery.</p>
					<p>Thankfully, tier five trophies are very good for experience - <i>very</i> good.</p>
					<p>That being said, your quests for level 80 are on the Island of Ice, a portal reachable only from the Outlands portal in Bristugo - <a href="http://www.istaria-lexica.de/Expedition_Camp" target="_blank">specifically at the expedition camp</a>. Here begins the  long Niesa's Fate questline at level 90, and a few other small quests at level 80. Be aware that Niesa's Fate leads up to you killing an Epic Boss, so be prepared to pull a group together. One of these quests gives an exceptionally good Tail Scale technique, though I would recommend saving it for a T6 tail scale post-ancienthood for casters.</p>
					<p>At level 85, you can pick up the beginnings of the Imperial Army questline, which eventually leads to obtaining the Ceremonial Chest Scale, one of the best  defensive pieces of armor in the game. This starts from the <a href="http://www.istaria-lexica.de/Imperial_Outpost" target="_blank">Imperial Outpost</a>
					<p>For level 90, the Iron Guard questline starts in Aughundell. You can also go to the <a href="http://www.istaria-lexica.de/Blackhammer_Farmstead" target="_blank">Blackhammer Farmstead<a> and pick up the quests there for a very good crystal (Saris Stone of Friendship, +250 ethereal armor and +175 health) and technique kit (Blackhammer Crest - +500 to Blight Resistance, 25% chance to reduce incoming melee and ranged damage by 20% from undead.)</p>
					<p>Finally, you can begin epic hunting - your daily quests are picked up at <a href="http://www.istaria-lexica.de/Eastern_Outpost" target="_blank">the Eastern Outpost</a>. While not an amazing source of experience, it is endgame content that brings the community together and prepares you for getting your best gear!</p>
					<p>At level 100, you can then take on the Ancient Rite of Passage... good luck, and have fun.</p>
		<a name="adventure"><header class="subsection border">The Rites of Passage</header></a>
			<p>When you reach a certain level as a dragon, you can do the most notable race-specific quests known as the adult and ancient rite of passages. These quests change your character between different life stages, allowing them to grow, as you likely know! These quests are considered epic quests, despite the adult not being max level, due to their length, time commitment, and number of bosses.</p>
			<p>I will not be going in depth into the exact steps of each questline, but I will be specifying the difference between the factions and the requirements below.</p>
				<a name="faction"><header class="subsection2 border">Helian or Lunus?</header></a>
					<p>A very common question I see in-game is whether to go Helian or Lunus. In the end, it is entirely a personal decision. The main deciding factors for everyone is between one of the three - the lore, the bonuses, or the difficulty.</p>
					<p><b>Lore:</b>The lore of the factions is described by Avariatus on New Trismus, but in short, the factions are a political divide in the Dragon race of Istaria. It is entirely based on how to deal with the naka'duskael - the biped races. Helians believe in guiding the bipeds to enlightenment, wishing to teach them the ways to be better and showing them to a brighter future. They want to take them under their wing as proteges. On the other hand, the Lunus are more militant and want to enslave and rule over the bipeds as Dragons did once before. They are subservient in the Lunus' eyes, cannot improve, and should be used as they are. This divide caused a massive schism, which culminated in the self-exile of the dragon Nyestra Helian and her followers to Chiconis. The Lunus remain in the dragon homeland of Dralk.</p>
					<p><b>Bonuses:</b> The factions have very little difference in terms of bonuses. For ascending to adult, you get an extremely minescule buff - Lunus gain +40 Flame Resistance and +20 Tooth and Claw. Helians gain +20 Spirit Resistance, +20 Ice Resistance, and +20 Primal. In the endgame, this means nothing - the difference of one or two damage per attack. The big difference is when you ascend to Ancient and you receive the Ancient crystal - the <a href="http://www.istaria-lexica.de/The_Fangs_of_Fury" target="_blank">Fangs of Fury</a> for Lunus or the <a href="http://www.istaria-lexica.de/The_Primal_Rage" target="_blank">Primal Rage</a>. The former, the Lunus crystal, is very useful for melee ancients. While their meta (most damaging) claws do not use it, it is still very useful to have if you are a melee attacker or still working towards that goal. On the flipside, the Helian crystal is exceptionally useful for casters and is used in their best claw, though it can be substituted for other crystals. In this aspect, Helian is 'required' for casters, but melee can go either way.</p>
					<p><b>Difficulty:</b> On the whole, the Lunus rite of passage is actually more difficult, contrary to popular belief. There are more bosses to fight and you also spend a lot more time running around. Helian is a bit shorter, on the whole, and spends more time in the same area than running around. On the flipside, Helian has more preparation - you need at least level 40 crafting to finish the Rite of Passage at level thirty. (See the <a href="http://istaraschosen.com/resources/ropcalculator.php" target="_blank">Rite of Passage calculator for details</a>). As a whole, <i>most</i> players end up doing Lunus because the crafting requirement can be very hard to surmount due to the length of time spent crafting.</p>
				<a name="rop"><header class="subsection2 border">Adult Rite of Passage</header></a>
					<p>The Adult rite of passage has the following requirements, officially:</p>
						<ul>
							<li>Level 30 Adventure</li>
							<li>Level 20 Crafting</li>
							<li>250,000 Hoard</li>
							<li>15 Days Since Creation</li>
						</ul>
					<p>In order to finish the quest, however, you will need a minimum of 300 transmutation skill (Lunus) or 450 spellcraft (Helian). These are the limiting factors in terms of craft, which translates to about craft level 30 and 40. Check out the <a href="http://istaraschosen.com/resources/ropcalculator.php" target="_blank">Rite of Passage calculator</a> to find out exactly what you need to do to reach these requirements. Even with these levels, though, you will need to be carried through the entire quest - everything in the quest is over level 40 at least.</p>
					<p>Recommended levels to take the Rite of Passage are below. You still can't solo it at these levels, but you can get far alone.</p>
						<ul>
							<li>Level 50 Adventure</li>
							<li>Level 30 (Lunus) / 35 (Helian) Crafting</li>
							<li>All ability quests to IV</li>
							<li>Techniqued T3 Scaleset</li>
						</ul>
				<a name="arop"><header class="subsection2 border">Ancient Rite of Passage</header></a>
					<p>The Ancient Rite of Passage has the official requirements:</p>
						<ul>
							<li>Level 100 Adventure</li>
							<li>100 Days Since Creation</li>
							<li>Accurate Breath IX, Tooth and  Claw IX, Primal Master IX</li>
						</ul>
					<p>These requirements are bare minimum and you can get far on it. There is no craft requirement, but if you want to be self-sufficient on the quest, you will need to be max craft. Below are what is recommended.</p>
						<ul>
							<li>Level 100 Adventure</li>
							<li>All ability quests to VII/VIII/IX</li>
							<li>Techniqued T5 Scaleset</li>
						</ul>
					<p>You cannot solo the Ancient Rite of Passage as easily as you can the Rite of Passage. Without lots of preperation and good gearing, it's very very unlikely you will get past the final boss - you can, however, solo up until that part if you play well enough. The final few bosses - known as the Rift Run - is usually a group activity, so feel free to ask for help. Others will be glad to come along.</p>
					
	</article>
	<!--BEGIN SIDEBAR -->
	<div class="sidebarbox">
		<?php include("../sidebar.html");?>
	</div>
	<!-- END SIDEBAR -->
</section>
</body>
</html>